// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./mysql-specific.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **MysqlSpecificTable**
 * @see {@link ./mysql-specific.as:5:18}
 */
export declare class MysqlSpecificTable {
  id: number
  age: number /* int */
  bio: string
  name: string
  updatedAt: number /* timestamp */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MysqlSpecificTable, MysqlSpecificTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MysqlSpecificTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "age": number /* int */
    "bio": string
    "name": string
    "updatedAt": number /* timestamp */
  }
  static __ownProps: {
    "id": number
    "age": number /* int */
    "bio": string
    "name": string
    "updatedAt": number /* timestamp */
  }
  
  static __pk: number
}
// prettier-ignore-end