// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./annotate-import-mutating.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { MyInterface } from "./annotate-nonmutating.as"
// prettier-ignore-end