// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./annotate-import.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { MyInterface } from "./annotate-nonmutating.as"

/**
 * Atscript annotate **ImportedAnnotated**
 * @see {@link ./annotate-import.as:3:32}
 */
export declare class ImportedAnnotated extends MyInterface {}
// prettier-ignore-end