// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./fractional-ref.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **FractionalRolesTable**
 * @see {@link ./fractional-ref.as:3:18}
 */
export declare class FractionalRolesTable {
  id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalRolesTable, FractionalRolesTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalRolesTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalBarrenTable**
 * @see {@link ./fractional-ref.as:8:18}
 */
export declare class FractionalBarrenTable {
  id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalBarrenTable, FractionalBarrenTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalBarrenTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalTarget2**
 * @see {@link ./fractional-ref.as:13:18}
 */
export declare class FractionalTarget2 {
  id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalTarget2, FractionalTarget2>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalTarget2>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalTarget1**
 * @see {@link ./fractional-ref.as:18:18}
 */
export declare class FractionalTarget1 {
  id: string
  fieldB: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalTarget1, FractionalTarget1>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalTarget1>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalBaselineTarget**
 * @see {@link ./fractional-ref.as:24:18}
 */
export declare class FractionalBaselineTarget {
  id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalBaselineTarget, FractionalBaselineTarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalBaselineTarget>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalFullTarget**
 * @see {@link ./fractional-ref.as:30:18}
 */
export declare class FractionalFullTarget {
  id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalFullTarget, FractionalFullTarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalFullTarget>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalShallowTarget**
 * @see {@link ./fractional-ref.as:37:18}
 */
export declare class FractionalShallowTarget {
  id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalShallowTarget, FractionalShallowTarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalShallowTarget>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceRoles**
 * @see {@link ./fractional-ref.as:41:18}
 */
export declare class FractionalSourceRoles {
  roleId: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceRoles, FractionalSourceRoles>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceRoles>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceBarren**
 * @see {@link ./fractional-ref.as:45:18}
 */
export declare class FractionalSourceBarren {
  barrenId: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceBarren, FractionalSourceBarren>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceBarren>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceNested**
 * @see {@link ./fractional-ref.as:49:18}
 */
export declare class FractionalSourceNested {
  fieldA: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceNested, FractionalSourceNested>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceNested>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceBaseline**
 * @see {@link ./fractional-ref.as:53:18}
 */
export declare class FractionalSourceBaseline {
  fk: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceBaseline, FractionalSourceBaseline>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceBaseline>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceFull**
 * @see {@link ./fractional-ref.as:57:18}
 */
export declare class FractionalSourceFull {
  fk: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceFull, FractionalSourceFull>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceFull>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **FractionalSourceShallow**
 * @see {@link ./fractional-ref.as:61:18}
 */
export declare class FractionalSourceShallow {
  fk: string /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FractionalSourceShallow, FractionalSourceShallow>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FractionalSourceShallow>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end