// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./intersections.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **IA**
 * @see {@link ./intersections.as:3:11}
 */
declare class IA {
  a: string
  b?: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IA, IA>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof IA>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **IB**
 * @see {@link ./intersections.as:12:11}
 */
declare class IB {
  b: number
  c?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IB, IB>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof IB>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript type **T**
 * @see {@link ./intersections.as:22:6}
 */
declare type T = IA & IB
declare namespace T {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeObject<keyof T, T>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof T>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}

/**
 * Atscript interface **I1**
 * @see {@link ./intersections.as:24:18}
 */
export declare class I1 {
  all: T
  a: T["a"]
  b: T["b"]
  c: T["c"]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof I1, I1>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof I1>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end