// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./jsonschema-defs.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Dog**
 * @see {@link ./jsonschema-defs.as:1:11}
 */
declare class Dog {
  petType: "dog"
  color: string
  name: string
  isHunt: boolean
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Dog, Dog>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Dog>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Cat**
 * @see {@link ./jsonschema-defs.as:8:11}
 */
declare class Cat {
  petType: "cat"
  color: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Cat, Cat>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Cat>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript type **DogCat**
 * @see {@link ./jsonschema-defs.as:15:13}
 */
export type DogCat = Dog | Cat
declare namespace DogCat {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<DogCat>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof DogCat>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}
// prettier-ignore-end