// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./jsonschema-deep.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **JsonDeep**
 * @see {@link ./jsonschema-deep.as:1:18}
 */
export declare class JsonDeep {
  s: string
  n: number
  c: string | number
  obj: {
    a: string
    b: number
    c: boolean
  }
  a: string[]
  aObj: {
    a: string
    b: number
    c: boolean
  }[]
  optional?: string
  optionalObj?: {
    a: string
    b: number
    c: boolean
  }
  deep: {
    deeper: {
      deepest: string
    }
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof JsonDeep, JsonDeep>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof JsonDeep>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end