export {
  defineConfig,
  AnnotationSpec,
  SemanticPrimitiveNode,
  Token,
  AnscriptDoc,
  build,
  BuildRepo,
  type TOutput,
  type TPluginOutput,
  type TOutputWithSource,
  type TAnscriptConfig,
  type TAnnotationSpecConfig,
  type TPrimitiveConfig,
  type TAnscriptPlugin,
} from '@anscript/core'
