export {
  defineConfig,
  AnnotationSpec,
  SemanticPrimitiveNode,
  Token,
  AtscriptDoc,
  build,
  BuildRepo,
  type TOutput,
  type TPluginOutput,
  type TOutputWithSource,
  type TAtscriptConfig,
  type TAnnotationSpecConfig,
  type TPrimitiveConfig,
  type TAtscriptPlugin,
} from '@atscript/core'
