// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./arrays-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArraysCollection**
 * @see {@link ./arrays-collection.as:3:18}
 */
export declare class ArraysCollection {
  primitive: string[]
  primitiveComplex: (number | string)[]
  withKey: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withKeyMerge: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withoutKey: {
    key: string
    value: string
    attribute?: string
  }[]
  withoutKeyMerge: {
    key: string
    value: string
    attribute: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArraysCollection, ArraysCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ArraysCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "primitive": string[]
    "primitiveComplex": never
    "withKey": never
    "withKey.key1": string
    "withKey.key2": string
    "withKey.value": string
    "withKey.attribute": string
    "withKeyMerge": never
    "withKeyMerge.key1": string
    "withKeyMerge.key2": string
    "withKeyMerge.value": string
    "withKeyMerge.attribute": string
    "withoutKey": never
    "withoutKey.key": string
    "withoutKey.value": string
    "withoutKey.attribute"?: string
    "withoutKeyMerge": never
    "withoutKeyMerge.key": string
    "withoutKeyMerge.value": string
    "withoutKeyMerge.attribute": string
    "_id": string /* objectId */
  }}
// prettier-ignore-end