// prettier-ignore-start
/* eslint-disable */
/// <reference path="./arrays-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArraysCollection**
 * @see {@link ./arrays-collection.as:2:18}
 */
export declare class ArraysCollection {
  primitive: string[]
  primitiveComplex: (number | string)[]
  withKey: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withKeyMerge: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withoutKey: {
    key: string
    value: string
    attribute?: string
  }[]
  withoutKeyMerge: {
    key: string
    value: string
    attribute: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArraysCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof ArraysCollection>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end