// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./arrays-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArraysCollection**
 * @see {@link ./arrays-collection.as:2:18}
 */
export declare class ArraysCollection {
  primitive: string[]
  primitiveComplex: (number | string)[]
  withKey: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withKeyMerge: {
    key1: string
    key2: string
    value: string
    attribute: string
  }[]
  withoutKey: {
    key: string
    value: string
    attribute?: string
  }[]
  withoutKeyMerge: {
    key: string
    value: string
    attribute: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArraysCollection, ArraysCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ArraysCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end