// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": boolean
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.required": { message?: string }
    "meta.default": string
    "meta.example": string
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "expect.array.key": boolean
    "emit.jsonSchema": boolean
    "db.table": string | true
    "db.schema": string
    "db.index.plain": ({ name?: string, sort?: string })[]
    "db.index.unique": (string | true)[]
    "db.index.fulltext": (string | true)[]
    "db.column": string
    "db.default.value": string
    "db.default.fn": string
    "db.ignore": boolean
    "db.mongo.collection": boolean
    "db.mongo.autoIndexes": boolean
    "db.mongo.index.text": number | true
    "db.mongo.search.dynamic": { analyzer?: string, fuzzy?: number }
    "db.mongo.search.static": ({ analyzer?: string, fuzzy?: number, indexName?: string })[]
    "db.mongo.search.text": ({ analyzer?: string, indexName?: string })[]
    "db.mongo.search.vector": { dimensions: number, similarity?: string, indexName?: string }
    "db.mongo.search.filter": ({ indexName: string })[]
    "db.mongo.patch.strategy": string
    "db.mongo.array.uniqueItems": boolean
    "ui.placeholder": string
    "ui.component": string
    "ui.hidden": boolean
    "ui.group": string
    "ui.order": number
    "ui.width": string
    "ui.icon": string
    "ui.hint": string
    "ui.disabled": boolean
    "ui.type": string
    "ui.attr": ({ key: string, value: string })[]
    "ui.class": (string)[]
    "ui.style": (string)[]
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "required" | "number" | "positive" | "negative" | "single" | "double" | "int" | "timestamp" | "created" | "updated" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom" | "mongo" | "objectId" | "vector"
}
// prettier-ignore-end