// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./flatten-test.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **FlattenTest**
 * @see {@link ./flatten-test.as:2:18}
 */
export declare class FlattenTest {
  level0: string
  nested: {
    level1: string
    array1: {
      level2: string
      array2: {
        level3: string
      }[]
    }[]
  }
  array0: {
    level1: string
  }[]
  complexArray: {
    field1: string
  } | {
    field1: number
    field2: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof FlattenTest, FlattenTest>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof FlattenTest>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end