// prettier-ignore-start
/* eslint-disable */
/// <reference path="./plugins.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **IdPlugin**
 * @see {@link ./plugins.as:2:18}
 */
export declare class IdPlugin {
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IdPlugin>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof IdPlugin>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}

/**
 * Atscript interface **UniqueItems**
 * @see {@link ./plugins.as:7:18}
 */
export declare class UniqueItems {
  str?: string[]
  strUnique?: string[]
  obj?: {
    a: string
    b: string
  }[]
  objUnique?: {
    a: string
    b: string
  }[]
  kObj?: {
    a: string
    b: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UniqueItems>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof UniqueItems>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end