// prettier-ignore-start
/* eslint-disable */
/// <reference path="./plugins.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **IdPlugin**
 * @see {@link ./plugins.as:2:18}
 */
export declare class IdPlugin {
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IdPlugin, IdPlugin>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof IdPlugin>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@ts.buildJsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace IdPlugin {
  type DataType = IdPlugin
}


/**
 * Atscript interface **UniqueItems**
 * @see {@link ./plugins.as:7:18}
 */
export declare class UniqueItems {
  str?: string[]
  strUnique?: string[]
  obj?: {
    a: string
    b: string
  }[]
  objUnique?: {
    a: string
    b: string
  }[]
  kObj?: {
    a: string
    b: string
  }[]
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UniqueItems, UniqueItems>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UniqueItems>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@ts.buildJsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace UniqueItems {
  type DataType = UniqueItems
}

// prettier-ignore-end