// prettier-ignore-start
/* eslint-disable */
/// <reference path="./simple-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SimpleCollection**
 * @see {@link ./simple-collection.as:2:18}
 */
export declare class SimpleCollection {
  name: string
  active: boolean
  occupation?: string
  tags?: string[]
  age: number
  address: {
    line1: string
    line2?: string
    city: string
    state: string
    zip: string
  }
  contacts: {
    email: string
    phone: string
  }
  nested?: {
    nested1?: {
      a?: number
      b?: string
    }
    nested2?: {
      c?: number
      d?: string
    }
  }
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SimpleCollection, SimpleCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SimpleCollection>
  static toJsonSchema: () => any
}
export declare namespace SimpleCollection {
  type DataType = SimpleCollection
}


/**
 * Atscript interface **MinimalCollection**
 * @see {@link ./simple-collection.as:35:18}
 */
export declare class MinimalCollection {
  name: string
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MinimalCollection, MinimalCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MinimalCollection>
  static toJsonSchema: () => any
}
export declare namespace MinimalCollection {
  type DataType = MinimalCollection
}


/**
 * Atscript interface **MinimalCollectionString**
 * @see {@link ./simple-collection.as:40:18}
 */
export declare class MinimalCollectionString {
  _id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MinimalCollectionString, MinimalCollectionString>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MinimalCollectionString>
  static toJsonSchema: () => any
}
export declare namespace MinimalCollectionString {
  type DataType = MinimalCollectionString
}

// prettier-ignore-end