// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./simple-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SimpleCollection**
 * @see {@link ./simple-collection.as:3:18}
 */
export declare class SimpleCollection {
  name: string
  active: boolean
  occupation?: string
  tags?: string[]
  age: number
  address: {
    line1: string
    line2?: string
    city: string
    state: string
    zip: string
  }
  contacts: {
    email: string
    phone: string
  }
  nested?: {
    nested1?: {
      a?: number
      b?: string
    }
    nested2?: {
      c?: number
      d?: string
    }
  }
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SimpleCollection, SimpleCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SimpleCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **MinimalCollection**
 * @see {@link ./simple-collection.as:37:18}
 */
export declare class MinimalCollection {
  name: string
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MinimalCollection, MinimalCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MinimalCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **MinimalCollectionString**
 * @see {@link ./simple-collection.as:43:18}
 */
export declare class MinimalCollectionString {
  _id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MinimalCollectionString, MinimalCollectionString>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MinimalCollectionString>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end