// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./meta-id-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **TodoCollection**
 * @see {@link ./meta-id-collection.as:3:18}
 */
export declare class TodoCollection {
  id: number
  title: string
  completed: boolean
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TodoCollection, TodoCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TodoCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "title": string
    "completed": boolean
    "_id": string /* objectId */
  }
  static __ownProps: {
    "id": number
    "title": string
    "completed": boolean
    "_id": string /* objectId */
  }
  
  static __pk: string /* objectId */ | number
}

/**
 * Atscript interface **ItemCollection**
 * @see {@link ./meta-id-collection.as:16:18}
 */
export declare class ItemCollection {
  code: string
  name: string
  _id: string /* objectId */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ItemCollection, ItemCollection>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ItemCollection>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "code": string
    "name": string
    "_id": string /* objectId */
  }
  static __ownProps: {
    "code": string
    "name": string
    "_id": string /* objectId */
  }
  
  static __pk: string /* objectId */ | string
}
// prettier-ignore-end