// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./no-mongo-collection.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **UserNoMongo**
 * @see {@link ./no-mongo-collection.as:2:18}
 */
export declare class UserNoMongo {
  id: number
  email: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UserNoMongo, UserNoMongo>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UserNoMongo>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "email": string
    "name": string
  }
  static __ownProps: {
    "id": number
    "email": string
    "name": string
  }
  
  static __pk: number | string
}
// prettier-ignore-end