// prettier-ignore-start
/* eslint-disable */
/// <reference path="./annotate-type.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript type **TString**
 * @see {@link ./annotate-type.as:2:13}
 */
export type TString = string | number
declare namespace TString {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<TAtscriptAnnotatedTypeConstructor, TString>
  const toJsonSchema: () => any
}

/**
 * Atscript annotate **TString2**
 * @see {@link ./annotate-type.as:8:28}
 */
export type TString2 = TString
declare namespace TString2 {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<TAtscriptAnnotatedTypeConstructor, TString2>
  const toJsonSchema: () => any
}

/**
 * Atscript type **TO**
 * @see {@link ./annotate-type.as:10:6}
 */
declare type TO = {
  name: string
  age: number
} | {
  kind: "abc" | "def"
}
declare namespace TO {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<TAtscriptAnnotatedTypeConstructor, TO>
  const toJsonSchema: () => any
}

/**
 * Atscript annotate **TO2**
 * @see {@link ./annotate-type.as:26:23}
 */
export type TO2 = TO
declare namespace TO2 {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<TAtscriptAnnotatedTypeConstructor, TO2>
  const toJsonSchema: () => any
}
// prettier-ignore-end