// prettier-ignore-start
/* eslint-disable */
/// <reference path="./annotate-import.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"
import { MyInterface } from "./annotate-nonmutating.as"

/**
 * Atscript annotate **ImportedAnnotated**
 * @see {@link ./annotate-import.as:3:32}
 */
export declare class ImportedAnnotated {
  name: string
  age: number
  email: string /* email */
  address: {
    street: string
    city: string
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ImportedAnnotated>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = ImportedAnnotated>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end