// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./annotate-deep-ref.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Contact**
 * @see {@link ./annotate-deep-ref.as:1:11}
 */
declare class Contact {
  phone: string
  email: string /* email */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Contact, Contact>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Contact>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Address**
 * @see {@link ./annotate-deep-ref.as:9:11}
 */
declare class Address {
  street: string
  contact: Contact
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Deep**
 * @see {@link ./annotate-deep-ref.as:16:18}
 */
export declare class Deep {
  name: string
  address: Address
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Deep, Deep>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Deep>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript annotate **AliasedDeep**
 * @see {@link ./annotate-deep-ref.as:32:25}
 */
export declare class AliasedDeep extends Deep {}
// prettier-ignore-end