// prettier-ignore-start
/* eslint-disable */
/// <reference path="./annotate-mutating.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **MyInterface**
 * @see {@link ./annotate-mutating.as:1:18}
 */
export declare class MyInterface {
  name: string
  age: number
  email: string /* email */
  address: {
    street: string
    city: string
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MyInterface, MyInterface>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MyInterface>
  static toJsonSchema: () => any
}
export declare namespace MyInterface {
  type DataType = MyInterface
}

// prettier-ignore-end