// prettier-ignore-start
/* eslint-disable */
/// <reference path="./annotate-type.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript type **TString**
 * @see {@link ./annotate-type.as:2:13}
 */
export type TString = string | number
declare namespace TString {
  type DataType = TString
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<TString>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TString, TString>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript annotate **TString2**
 * @see {@link ./annotate-type.as:8:28}
 */
export type TString2 = TString
declare namespace TString2 {
  type DataType = TString2
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<TString2>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TString2, TString2>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript type **TO**
 * @see {@link ./annotate-type.as:10:6}
 */
declare type TO = {
  name: string
  age: number
} | {
  kind: "abc" | "def"
}
declare namespace TO {
  type DataType = TO
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<TO>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TO, TO>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript annotate **TO2**
 * @see {@link ./annotate-type.as:26:23}
 */
export type TO2 = TO
declare namespace TO2 {
  type DataType = TO2
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<TO2>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TO2, TO2>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}
// prettier-ignore-end