// prettier-ignore-start
/* eslint-disable */
/// <reference path="./annotate-mutating.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **MyInterface**
 * @see {@link ./annotate-mutating.as:1:18}
 */
export declare class MyInterface {
  name: string
  age: number
  email: string /* email */
  address: {
    street: string
    city: string
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MyInterface>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof MyInterface>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end