// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./db-table-flat.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Address**
 * @see {@link ./db-table-flat.as:1:11}
 */
declare class Address {
  street: string
  city: string
  zip?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **MyEntity**
 * @see {@link ./db-table-flat.as:8:18}
 */
export declare class MyEntity {
  id: string
  name: string
  address: {
    street: string
    city: string
    zip?: string
  }
  tags: string[]
  contacts: {
    name: string
    email: string
  }[]
  home: Address
  optional?: number
  metadata: {
    key: string
    value: string
  }
  items: {
    label: string
  }[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MyEntity, MyEntity>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MyEntity>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "name": string
    "address": never
    "address.street": string
    "address.city": string
    "address.zip"?: string
    "tags": string[]
    "contacts": never
    "contacts.name": string
    "contacts.email": string
    "home": never
    "home.street": string
    "home.city": string
    "home.zip"?: string
    "optional"?: number
    "metadata": string
    "items": string
  }
  static __ownProps: {
    "id": string
    "name": string
    "address": never
    "address.street": string
    "address.city": string
    "address.zip"?: string
    "tags": string[]
    "contacts": never
    "contacts.name": string
    "contacts.email": string
    "home": never
    "home.street": string
    "home.city": string
    "home.zip"?: string
    "optional"?: number
    "metadata": string
    "items": string
  }
}

/**
 * Atscript interface **NonDbInterface**
 * @see {@link ./db-table-flat.as:34:18}
 */
export declare class NonDbInterface {
  field: string
  nested: {
    inner: number
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NonDbInterface, NonDbInterface>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NonDbInterface>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end