// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./db-table-pk.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SinglePk**
 * @see {@link ./db-table-pk.as:2:18}
 */
export declare class SinglePk {
  id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SinglePk, SinglePk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SinglePk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "name": string
  }
  static __ownProps: {
    "id": string
    "name": string
  }
  
  static __pk: string
}

/**
 * Atscript interface **CompoundPk**
 * @see {@link ./db-table-pk.as:9:18}
 */
export declare class CompoundPk {
  userId: string
  orderId: number
  amount: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CompoundPk, CompoundPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CompoundPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "userId": string
    "orderId": number
    "amount": number
  }
  static __ownProps: {
    "userId": string
    "orderId": number
    "amount": number
  }
  
  static __pk: {
    userId: string
    orderId: number
  }
}

/**
 * Atscript interface **NoPk**
 * @see {@link ./db-table-pk.as:18:18}
 */
export declare class NoPk {
  name: string
  value: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NoPk, NoPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NoPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "name": string
    "value": number
  }
  static __ownProps: {
    "name": string
    "value": number
  }
}

/**
 * Atscript interface **MongoSinglePk**
 * @see {@link ./db-table-pk.as:25:18}
 */
export declare class MongoSinglePk {
  id: number
  name: string
  _id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MongoSinglePk, MongoSinglePk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MongoSinglePk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "_id": string
  }
  static __ownProps: {
    "id": number
    "name": string
    "_id": string
  }
  
  static __pk: string | number
}

/**
 * Atscript interface **MongoCompoundPk**
 * @see {@link ./db-table-pk.as:34:18}
 */
export declare class MongoCompoundPk {
  userId: string
  orderId: number
  amount: number
  _id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MongoCompoundPk, MongoCompoundPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MongoCompoundPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "userId": string
    "orderId": number
    "amount": number
    "_id": string
  }
  static __ownProps: {
    "userId": string
    "orderId": number
    "amount": number
    "_id": string
  }
  
  static __pk: string | {
    userId: string
    orderId: number
  }
}

/**
 * Atscript interface **MongoNoPk**
 * @see {@link ./db-table-pk.as:45:18}
 */
export declare class MongoNoPk {
  name: string
  value: number
  _id: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MongoNoPk, MongoNoPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MongoNoPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "name": string
    "value": number
    "_id": string
  }
  static __ownProps: {
    "name": string
    "value": number
    "_id": string
  }
  
  static __pk: string
}

/**
 * Atscript interface **MongoIdAsMetaId**
 * @see {@link ./db-table-pk.as:53:18}
 */
export declare class MongoIdAsMetaId {
  _id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MongoIdAsMetaId, MongoIdAsMetaId>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MongoIdAsMetaId>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "_id": string
    "name": string
  }
  static __ownProps: {
    "_id": string
    "name": string
  }
  
  static __pk: string
}

/**
 * Atscript interface **PkWithUnique**
 * @see {@link ./db-table-pk.as:60:18}
 */
export declare class PkWithUnique {
  id: number
  email: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PkWithUnique, PkWithUnique>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof PkWithUnique>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "email": string
    "name": string
  }
  static __ownProps: {
    "id": number
    "email": string
    "name": string
  }
  
  static __pk: number | string
}

/**
 * Atscript interface **UniqueOnly**
 * @see {@link ./db-table-pk.as:69:18}
 */
export declare class UniqueOnly {
  name: string
  code: string
  num: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UniqueOnly, UniqueOnly>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UniqueOnly>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "name": string
    "code": string
    "num": number
  }
  static __ownProps: {
    "name": string
    "code": string
    "num": number
  }
  
  static __pk: string | number
}

/**
 * Atscript interface **CompoundUnique**
 * @see {@link ./db-table-pk.as:78:18}
 */
export declare class CompoundUnique {
  id: number
  tenantId: string
  email: string
  slug: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CompoundUnique, CompoundUnique>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CompoundUnique>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "tenantId": string
    "email": string
    "slug": string
  }
  static __ownProps: {
    "id": number
    "tenantId": string
    "email": string
    "slug": string
  }
  
  static __pk: number | string
}
// prettier-ignore-end