// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./db-table-pk.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **SinglePk**
 * @see {@link ./db-table-pk.as:2:18}
 */
export declare class SinglePk {
  id: string
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SinglePk, SinglePk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SinglePk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "name": string
  }
  static __pk: string
}

/**
 * Atscript interface **CompoundPk**
 * @see {@link ./db-table-pk.as:9:18}
 */
export declare class CompoundPk {
  userId: string
  orderId: number
  amount: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CompoundPk, CompoundPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CompoundPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "userId": string
    "orderId": number
    "amount": number
  }
  static __pk: {
    userId: string
    orderId: number
  }}

/**
 * Atscript interface **NoPk**
 * @see {@link ./db-table-pk.as:18:18}
 */
export declare class NoPk {
  name: string
  value: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NoPk, NoPk>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NoPk>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "name": string
    "value": number
  }}
// prettier-ignore-end