// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./db-table-agg.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Order**
 * @see {@link ./db-table-agg.as:2:18}
 */
export declare class Order {
  id: number
  status: string
  currency: string
  amount: number
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Order, Order>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Order>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "status": string
    "currency": string
    "amount": number
    "name": string
  }
  static __ownProps: {
    "id": number
    "status": string
    "currency": string
    "amount": number
    "name": string
  }
  
  static __pk: number
  
  static __dim: "status" | "currency"
  static __measure: "amount"
}

/**
 * Atscript interface **Product**
 * @see {@link ./db-table-agg.as:15:18}
 */
export declare class Product {
  id: number
  name: string
  price: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Product, Product>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Product>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "price": number
  }
  static __ownProps: {
    "id": number
    "name": string
    "price": number
  }
  
  static __pk: number
}
// prettier-ignore-end