// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "imports.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';
import { User } from './multiple-interface';
import { TPrimitive, TNumber } from './type';

export class People {
  groupName!: TPrimitive;
  
  size!: TNumber;
  
  users!: User[];
  
  static __is_anscript_annotated_type = true;
  
  static type: TAnscriptTypeObject = {
    kind: "object",
    type: People,
    props: new Map(),
  };
  
  static metadata = {};
}

//#region Annotations for People
{ // People["groupName"]
  const $$md_groupName = defineAnnotatedType({
    type: {},
    metadata: {},
  });
  People.type.props.set("groupName", $$md_groupName);
}{ // People["size"]
  const $$md_size = defineAnnotatedType({
    type: {},
    metadata: {},
  });
  People.type.props.set("size", $$md_size);
}{ // People["users"]
  const $$md_users = defineAnnotatedType({
    type: {
      kind: "array",
      of: {},
    },
    metadata: {},
  });
  People.type.props.set("users", $$md_users);
}
//#endregion

// prettier-ignore-end
