/// <reference path="./imports.as" />
// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript
 * Do not edit this file!
 */

import type { TAnscriptTypeObject } from "@anscript/typescript"
import { User } from "./multiple-interface.as"
import { TPrimitive, TNumber } from "./type.as"

/**
 * Anscript interface **People**
 * @see {@link ./imports.as:5:18}
 */
export declare class People {
  groupName: TPrimitive
  size: TNumber
  users: User[]
  static __is_anscript_annotated_type: boolean
  static type: TAnscriptTypeObject
  static metadata: Map<string, unknown>
}
// prettier-ignore-end