// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "imports.as".
 * Do not edit this file!
*/
import { User } from './multiple-interface';
import { TPrimitive, TNumber } from './type';

export class People {
  groupName: TPrimitive;
  
  size: TNumber;
  
  users: User[];
  
  static get __anscriptMeta(): any;
}

// prettier-ignore-end
