// prettier-ignore-start
/* eslint-disable */
/// <reference path="./inherit-chain.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator } from "@atscript/typescript"

/**
 * Atscript type **TType**
 * @see {@link ./inherit-chain.as:6:6}
 */
declare type TType = string
declare namespace TType {
  const __is_anscript_annotated_type: true
  const type: TAtscriptTypeFinal
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: () => Validator
}

/**
 * Atscript interface **I1**
 * @see {@link ./inherit-chain.as:8:11}
 */
declare class I1 {
  prop?: string
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof I1>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: () => Validator
}

/**
 * Atscript interface **I2**
 * @see {@link ./inherit-chain.as:15:18}
 */
export declare class I2 {
  prop?: string /* prop */
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof I2>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end