// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-from-type.as"
 * Do not edit this file!
 */

declare type TFirstName = string

declare type TLastName = string

declare type TAge = number

export declare class ITarget {
  firstName: TFirstName
  lastName?: TLastName
  age: TAge
}
// prettier-ignore-end