// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-metadata.as"
 * Do not edit this file!
 */

declare class ISource {
  firstName: string
  lastName: string
  age: number
}

export declare class ITarget {
  firstName: ISource["firstName"]
  lastName?: ISource["lastName"]
  age: ISource["age"]
}
// prettier-ignore-end