// prettier-ignore-start
/* eslint-disable */
/// <reference path="./inherit-from-type.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TMetadataMap, Validator } from "@atscript/typescript"

/**
 * Atscript type **TFirstName**
 * @see {@link ./inherit-from-type.as:4:6}
 */
declare type TFirstName = string

/**
 * Atscript type **TLastName**
 * @see {@link ./inherit-from-type.as:7:6}
 */
declare type TLastName = string

/**
 * Atscript type **TAge**
 * @see {@link ./inherit-from-type.as:10:6}
 */
declare type TAge = number

/**
 * Atscript interface **ITarget**
 * @see {@link ./inherit-from-type.as:13:18}
 */
export declare class ITarget {
  firstName: string
  lastName?: string
  age: number
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ITarget, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end