/// <reference path="./inherit-metadata.as" />
// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript
 * Do not edit this file!
 */

import type { TAnscriptTypeObject, TMetadataMap, Validator } from "@ts-anscript/typescript"

/**
 * Anscript interface **ISource**
 * @see {@link ./inherit-metadata.as:1:11}
 */
declare class ISource {
  firstName: string
  lastName: string
  age: number
  static __is_anscript_annotated_type: true
  static type: TAnscriptTypeObject<keyof ISource, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}

/**
 * Anscript interface **ITarget**
 * @see {@link ./inherit-metadata.as:14:18}
 */
export declare class ITarget {
  firstName: string /* firstName */
  lastName?: string /* lastName */
  age: number /* age */
  static __is_anscript_annotated_type: true
  static type: TAnscriptTypeObject<keyof ITarget, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end