/// <reference path="./inherit-from-type.as" />
// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript
 * Do not edit this file!
 */

import type { TAnscriptTypeObject, TMetadataMap, Validator } from "@ts-anscript/typescript"

/**
 * Anscript type **TFirstName**
 * @see {@link ./inherit-from-type.as:4:6}
 */
declare type TFirstName = string

/**
 * Anscript type **TLastName**
 * @see {@link ./inherit-from-type.as:7:6}
 */
declare type TLastName = string

/**
 * Anscript type **TAge**
 * @see {@link ./inherit-from-type.as:10:6}
 */
declare type TAge = number

/**
 * Anscript interface **ITarget**
 * @see {@link ./inherit-from-type.as:13:18}
 */
export declare class ITarget {
  firstName: string
  lastName?: string
  age: number
  static __is_anscript_annotated_type: true
  static type: TAnscriptTypeObject<keyof ITarget, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end