// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-chain.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

declare type TType = string;

declare class I1 {
  prop?: TType;
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

export class I2 {
  prop?: I1["prop"];
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

// prettier-ignore-end
