// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-metadata.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

declare class ISource {
  firstName: string;
  
  lastName: string;
  
  age: number;
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

export class ITarget {
  firstName: ISource["firstName"];
  
  lastName?: ISource["lastName"];
  
  age: ISource["age"];
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

// prettier-ignore-end
