// prettier-ignore-start
/* eslint-disable */
/// <reference path="./inherit-metadata.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ISource**
 * @see {@link ./inherit-metadata.as:1:11}
 */
declare class ISource {
  firstName: string
  lastName: string
  age: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ISource, ISource>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ISource>
  static toJsonSchema: () => any
}
declare namespace ISource {
  type DataType = ISource
}


/**
 * Atscript interface **ITarget**
 * @see {@link ./inherit-metadata.as:14:18}
 */
export declare class ITarget {
  firstName: string /* firstName */
  lastName?: string /* lastName */
  age: number /* age */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ITarget, ITarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ITarget>
  static toJsonSchema: () => any
}
export declare namespace ITarget {
  type DataType = ITarget
}

// prettier-ignore-end