/**
 * 🪄 This file was generated by Anscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AnscriptMetadata {
    label: string
    min: number
    required: boolean
  }
}
