// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": string | true
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.placeholder": string
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.isKey": boolean
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.filled": { message?: string }
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "emit.jsonSchema": boolean
    label: string
    labelOptional: string | true
    mul: (number)[]
    mulOptional: (number | true)[]
    mulAppend: (string)[]
    obj: { prop1: string, prop2?: number, prop3?: boolean }
    min: number
    required: boolean
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "filled" | "number" | "positive" | "negative" | "single" | "double" | "int" | "timestamp" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom"
}
// prettier-ignore-end