// prettier-ignore-start
/* eslint-disable */
/// <reference path="./inherit-from-type.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript type **TFirstName**
 * @see {@link ./inherit-from-type.as:4:6}
 */
declare type TFirstName = string
declare namespace TFirstName {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<TFirstName>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TFirstName>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript type **TLastName**
 * @see {@link ./inherit-from-type.as:7:6}
 */
declare type TLastName = string
declare namespace TLastName {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<TLastName>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TLastName>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript type **TAge**
 * @see {@link ./inherit-from-type.as:10:6}
 */
declare type TAge = number
declare namespace TAge {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<TAge>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TAge>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript interface **ITarget**
 * @see {@link ./inherit-from-type.as:13:18}
 */
export declare class ITarget {
  firstName: string
  lastName?: string
  age: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ITarget, ITarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ITarget>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end