// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": boolean
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.required": { message?: string }
    "meta.default": string
    "meta.example": string
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "expect.array.key": boolean
    "emit.jsonSchema": boolean
    "db.table": string | true
    "db.schema": string
    "db.index.plain": ({ name?: string, sort?: string })[]
    "db.index.unique": (string | true)[]
    "db.index.fulltext": (string | true)[]
    "db.column": string
    "db.default.value": string
    "db.default.fn": string
    "db.ignore": boolean
    "ui.placeholder": string
    "ui.component": string
    "ui.hidden": boolean
    "ui.group": string
    "ui.order": number
    "ui.width": string
    "ui.icon": string
    "ui.hint": string
    "ui.disabled": boolean
    "ui.type": string
    "ui.attr": ({ key: string, value: string })[]
    "ui.class": (string)[]
    "ui.style": (string)[]
    label: string
    labelOptional: string | true
    mul: (number)[]
    mulOptional: (number | true)[]
    mulAppend: (string)[]
    obj: { prop1: string, prop2?: number, prop3?: boolean }
    fromTType: boolean
    from: string
    pass1: string
    pass2: string
    pass3: string
    fromI1: boolean
    fromI2: boolean
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "required" | "number" | "positive" | "negative" | "single" | "double" | "int" | "timestamp" | "created" | "updated" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom"
}
// prettier-ignore-end