// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-chain.as"
 * Do not edit this file!
 */

declare type TType = string

declare class I1 {
  prop?: TType
}

export declare class I2 {
  prop?: I1["prop"]
}
// prettier-ignore-end