// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "inherit-from-type.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

type TFirstName = string;

type TLastName = string;

type TAge = number;

export class ITarget {
  firstName!: TFirstName;
  
  lastName?: TLastName;
  
  age!: TAge;
  
  static __is_anscript_annotated_type = true;
  
  static type: TAnscriptTypeObject = {
    kind: "object",
    type: ITarget,
    props: new Map(),
  };
  
  static metadata = {};
}

//#region Annotations for ITarget
{ // ITarget["firstName"]
  const $$md_firstName = defineAnnotatedType({
    type: {
      kind: "final",
      designType: "string",
      type: String,
    },
    metadata: {
      label: "First Name",
    },
  });
  ITarget.type.props.set("firstName", $$md_firstName);
}{ // ITarget["lastName"]
  const $$md_lastName = defineAnnotatedType({
    type: {
      kind: "final",
      designType: "string",
      type: String,
    },
    metadata: {
      label: "Last Name (optional)",
      required: false,
    },
  });
  ITarget.type.props.set("lastName", $$md_lastName);
}{ // ITarget["age"]
  const $$md_age = defineAnnotatedType({
    type: {
      kind: "final",
      designType: "number",
      type: Number,
    },
    metadata: {
      min: 18,
    },
  });
  ITarget.type.props.set("age", $$md_age);
}
//#endregion

// prettier-ignore-end
