// prettier-ignore-start
/* eslint-disable */
/// <reference path="./inherit-metadata.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ISource**
 * @see {@link ./inherit-metadata.as:1:11}
 */
declare class ISource {
  firstName: string
  lastName: string
  age: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ISource>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof ISource>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}

/**
 * Atscript interface **ITarget**
 * @see {@link ./inherit-metadata.as:14:18}
 */
export declare class ITarget {
  firstName: string /* firstName */
  lastName?: string /* lastName */
  age: number /* age */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ITarget>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof ITarget>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end