// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "interface-metadata.as"
 * Do not edit this file!
 */

export declare class WithMetadata {
  prop1: string
  "prop-2": number
  obj: {
    prop3: string
    prop4: string
    nested2: {
      nested3: {
        a: number
        b: string
        d: boolean
        e: null
        f: undefined
      }
    }
  }
}
// prettier-ignore-end