// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "interface.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

export class PublicInterface {
  primitive: string;
  
  pirmiitiveUn: string | number;
  
  interger: number;
  
  literal: "value";
  
  number: 5;
  
  tuple1: [string];
  
  tuple2: [string, string];
  
  tupleArray: [string, string][];
  
  array: string[];
  
  array2: string[][];
  
  array3: string[][][];
  
  complexArray: (string | number)[];
  
  complexArray2: ((string | number)[])[];
  
  complexArray3: (((string | number)[])[])[];
  
  complexArray4: string | number[];
  
  complexArray5: string[] | number;
  
  object: {
    prop1: string;
    prop2?: number;
    nested: {
      prop3: boolean;
      prop4?: boolean;
    };
  };
  
  optional?: string;
  
  objectUnion1: {
    a: "a";
  } | string;
  
  objectUnion2: string | {
    a: "a";
  };
  
  objectIntersection: {
    a: "a";
  } & {
    b: "b";
  };
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

// prettier-ignore-end
