/// <reference path="./interface-metadata.as" />
// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript
 * Do not edit this file!
 */

import type { TAnscriptTypeObject, TMetadataMap, Validator } from "@anscript/typescript"

/**
 * Anscript interface **WithMetadata**
 * @see {@link ./interface-metadata.as:4:18}
 */
export declare class WithMetadata {
  prop1: string
  "prop-2": int
  obj: {
    prop3: string
    prop4: string
    nested2: {
      nested3: {
        a: float
        b: string
        d: true
        e: null
        f: undefined
      }
    }
  }
  static __is_anscript_annotated_type: boolean
  static type: TAnscriptTypeObject<keyof WithMetadata>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end