// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "interface-metadata.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

export class WithMetadata {
  prop1: string;
  
  "prop-2": number;
  
  obj: {
    prop3: string;
    prop4: string;
    nested2: {
      nested3: {
        a: number;
        b: string;
        d: boolean;
        e: null;
        f: undefined;
      };
    };
  };
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

// prettier-ignore-end
