// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "interface-metadata.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

export class WithMetadata {
  prop1!: string;
  
  "prop-2"!: number;
  
  obj!: {
    prop3: string;
    prop4: string;
    nested2: {
      nested3: {
        a: number;
        b: string;
        d: boolean;
        e: null;
        f: undefined;
      };
    };
  };
  
  static __is_anscript_annotated_type = true;
  
  static type: TAnscriptTypeObject = {
    kind: "object",
    type: WithMetadata,
    props: new Map(),
  };
  
  static metadata = {
    id: "interface-with-metadata",
    long: {
      nested: {
        name: "WithMetadata",
      },
    },
    bool: {
      flag: true,
    },
  };
}

//#region Annotations for WithMetadata
{ // WithMetadata["prop1"]
  const $$md_prop1 = defineAnnotatedType({
    type: {
      kind: "final",
      designType: "string",
      type: String,
    },
    metadata: {
      label: "Prop1",
    },
  });
  WithMetadata.type.props.set("prop1", $$md_prop1);
}{ // WithMetadata["prop-2"]
  const $$md_prop2 = defineAnnotatedType({
    type: {
      kind: "final",
      designType: "number",
      type: Number,
    },
    metadata: {
      long: {
        nested: {
          name: "Prop-2",
          name2: "Prop-2-2",
        },
      },
    },
  });
  WithMetadata.type.props.set("prop-2", $$md_prop2);
}{ // WithMetadata["obj"]
  const $$md_obj = defineAnnotatedType({
    type: {
      kind: "object",
      type: Object,
      props: new Map(),
    },
    metadata: {
      nested: true,
    },
  });
  WithMetadata.type.props.set("obj", $$md_obj);

  //#region Annotations for WithMetadata["obj"]
  { // WithMetadata["obj"]["prop3"]
    const $$md_prop3 = defineAnnotatedType({
      type: {
        kind: "final",
        designType: "string",
        type: String,
      },
      metadata: {
        label: "Prop3",
      },
    });
    $$md_obj.type.props.set("prop3", $$md_prop3);
  }{ // WithMetadata["obj"]["prop4"]
    const $$md_prop4 = defineAnnotatedType({
      type: {
        kind: "final",
        designType: "string",
        type: String,
      },
      metadata: {
        label: "Prop4",
      },
    });
    $$md_obj.type.props.set("prop4", $$md_prop4);
  }{ // WithMetadata["obj"]["nested2"]
    const $$md_nested2 = defineAnnotatedType({
      type: {
        kind: "object",
        type: Object,
        props: new Map(),
      },
      metadata: {},
    });
    $$md_obj.type.props.set("nested2", $$md_nested2);

    //#region Annotations for WithMetadata["obj"]["nested2"]
    { // WithMetadata["obj"]["nested2"]["nested3"]
      const $$md_nested3 = defineAnnotatedType({
        type: {
          kind: "object",
          type: Object,
          props: new Map(),
        },
        metadata: {},
      });
      $$md_nested2.type.props.set("nested3", $$md_nested3);

      //#region Annotations for WithMetadata["obj"]["nested2"]["nested3"]
      { // WithMetadata["obj"]["nested2"]["nested3"]["a"]
        const $$md_a = defineAnnotatedType({
          type: {
            kind: "final",
            designType: "number",
            type: Number,
          },
          metadata: {},
        });
        $$md_nested3.type.props.set("a", $$md_a);
      }{ // WithMetadata["obj"]["nested2"]["nested3"]["b"]
        const $$md_b = defineAnnotatedType({
          type: {
            kind: "final",
            designType: "string",
            type: String,
          },
          metadata: {},
        });
        $$md_nested3.type.props.set("b", $$md_b);
      }{ // WithMetadata["obj"]["nested2"]["nested3"]["d"]
        const $$md_d = defineAnnotatedType({
          type: {
            kind: "final",
            designType: "boolean",
            type: Boolean,
          },
          metadata: {},
        });
        $$md_nested3.type.props.set("d", $$md_d);
      }{ // WithMetadata["obj"]["nested2"]["nested3"]["e"]
        const $$md_e = defineAnnotatedType({
          type: {
            kind: "final",
            designType: "null",
            type: Object,
          },
          metadata: {},
        });
        $$md_nested3.type.props.set("e", $$md_e);
      }{ // WithMetadata["obj"]["nested2"]["nested3"]["f"]
        const $$md_f = defineAnnotatedType({
          type: {
            kind: "final",
            designType: "undefined",
            type: undefined,
          },
          metadata: {},
        });
        $$md_nested3.type.props.set("f", $$md_f);
      }
      //#endregion
    }
    //#endregion
  }
  //#endregion
}
//#endregion

// prettier-ignore-end
