// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    "meta.label": string
    "meta.id": boolean
    "meta.description": string
    "meta.documentation": (string)[]
    "meta.sensitive": boolean
    "meta.readonly": boolean
    "meta.required": { message?: string }
    "meta.default": string
    "meta.example": string
    "expect.minLength": { length: number, message?: string }
    "expect.maxLength": { length: number, message?: string }
    "expect.min": { minValue: number, message?: string }
    "expect.max": { maxValue: number, message?: string }
    "expect.int": boolean
    "expect.pattern": ({ pattern: string, flags?: string, message?: string })[]
    "expect.array.uniqueItems": { message?: string }
    "expect.array.key": { message?: string }
    "emit.jsonSchema": boolean
    label: string
    labelOptional: string | true
    mul: (number)[]
    mulOptional: (number | true)[]
    mulAppend: (string)[]
    obj: { prop1: string, prop2?: number, prop3?: boolean }
    "long.nested.name": string
    "long.nested.name2": string
    nested: boolean
    id: string
    "bool.flag": boolean
  }
  type AtscriptPrimitiveTags = "never" | "string" | "email" | "phone" | "date" | "isoDate" | "uuid" | "url" | "ipv4" | "ipv6" | "ip" | "char" | "required" | "number" | "positive" | "negative" | "single" | "double" | "int" | "int8" | "int16" | "int32" | "int64" | "uint8" | "byte" | "uint16" | "port" | "uint32" | "uint64" | "timestamp" | "created" | "updated" | "decimal" | "boolean" | "true" | "false" | "null" | "void" | "undefined" | "phantom"
}
// prettier-ignore-end