// prettier-ignore-start
/* eslint-disable */
/// <reference path="./intersections.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TMetadataMap, Validator } from "@atscript/typescript"

/**
 * Atscript interface **IA**
 * @see {@link ./intersections.as:3:11}
 */
declare class IA {
  a: string
  b?: number
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IA, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}

/**
 * Atscript interface **IB**
 * @see {@link ./intersections.as:12:11}
 */
declare class IB {
  b: number
  c?: string
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IB, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}

/**
 * Atscript type **T**
 * @see {@link ./intersections.as:22:6}
 */
declare type T = IA & IB

/**
 * Atscript interface **I1**
 * @see {@link ./intersections.as:24:18}
 */
export declare class I1 {
  all: T
  a: T["a"]
  b: T["b"]
  c: T["c"]
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof I1, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end