// prettier-ignore-start
/* eslint-disable */
/// <reference path="./interface-metadata.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript"

/**
 * Atscript interface **WithMetadata**
 * @see {@link ./interface-metadata.as:4:18}
 */
export declare class WithMetadata {
  prop1: string
  "prop-2": number /* int */
  obj: {
    prop3: string
    prop4: string
    nested2: {
      nested3: {
        a: number /* double */
        b: string
        d: boolean /* true */
        e: null
        f: undefined
      }
    }
  }
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof WithMetadata>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = WithMetadata>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}

/**
 * Atscript type **SomeType**
 * @see {@link ./interface-metadata.as:42:13}
 */
export type SomeType = {
  a: "b"
}
declare namespace SomeType {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeObject<keyof SomeType>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: <TT extends TAtscriptAnnotatedTypeConstructor = SomeType>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}
// prettier-ignore-end