import { defineAnnotatedType as $ } from "@anscript/typescript"

export class PublicInterface {}
$("object", PublicInterface)
  .prop(
    "primitive",
    $()
      .designType("string")
      .type(String)
      .$type
  ).prop(
    "pirmiitiveUn",
    $("union")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .item($()
          .designType("number")
          .type(Number)
          .$type)
      .$type
  ).prop(
    "interger",
    $()
      .designType("number")
      .type(Number)
      .$type
  ).prop(
    "literal",
    $()
      .designType("string")
      .type(String)
      .value("value")
      .$type
  ).prop(
    "number",
    $()
      .designType("number")
      .type(Number)
      .value(5)
      .$type
  ).prop(
    "tuple1",
    $("tuple")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .$type
  ).prop(
    "tuple2",
    $("tuple")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .$type
  ).prop(
    "tupleArray",
    $("array")
      .of($("tuple")
          .item($()
              .designType("string")
              .type(String)
              .$type)
          .item($()
              .designType("string")
              .type(String)
              .$type)
          .$type)
      .$type
  ).prop(
    "array",
    $("array")
      .of($()
          .designType("string")
          .type(String)
          .$type)
      .$type
  ).prop(
    "array2",
    $("array")
      .of($("array")
          .of($()
              .designType("string")
              .type(String)
              .$type)
          .$type)
      .$type
  ).prop(
    "array3",
    $("array")
      .of($("array")
          .of($("array")
              .of($()
                  .designType("string")
                  .type(String)
                  .$type)
              .$type)
          .$type)
      .$type
  ).prop(
    "complexArray",
    $("array")
      .of($("union")
          .item($()
              .designType("string")
              .type(String)
              .$type)
          .item($()
              .designType("number")
              .type(Number)
              .$type)
          .$type)
      .$type
  ).prop(
    "complexArray2",
    $("array")
      .of($("array")
          .of($("union")
              .item($()
                  .designType("string")
                  .type(String)
                  .$type)
              .item($()
                  .designType("number")
                  .type(Number)
                  .$type)
              .$type)
          .$type)
      .$type
  ).prop(
    "complexArray3",
    $("array")
      .of($("array")
          .of($("array")
              .of($("union")
                  .item($()
                      .designType("string")
                      .type(String)
                      .$type)
                  .item($()
                      .designType("number")
                      .type(Number)
                      .$type)
                  .$type)
              .$type)
          .$type)
      .$type
  ).prop(
    "complexArray4",
    $("union")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .item($("array")
          .of($()
              .designType("number")
              .type(Number)
              .$type)
          .$type)
      .$type
  ).prop(
    "complexArray5",
    $("union")
      .item($("array")
          .of($()
              .designType("string")
              .type(String)
              .$type)
          .$type)
      .item($()
          .designType("number")
          .type(Number)
          .$type)
      .$type
  ).prop(
    "object",
    $("object")
      .prop(
        "prop1",
        $()
          .designType("string")
          .type(String)
          .$type
      ).prop(
        "prop2",
        $()
          .designType("number")
          .type(Number)
          .optional()
          .$type
      ).prop(
        "nested",
        $("object")
          .prop(
            "prop3",
            $()
              .designType("boolean")
              .type(Boolean)
              .$type
          ).prop(
            "prop4",
            $()
              .designType("boolean")
              .type(Boolean)
              .optional()
              .$type
          )
          .$type
      )
      .$type
  ).prop(
    "optional",
    $()
      .designType("string")
      .type(String)
      .optional()
      .$type
  ).prop(
    "objectUnion1",
    $("union")
      .item($("object")
          .prop(
            "a",
            $()
              .designType("string")
              .type(String)
              .value("a")
              .$type
          )
          .$type)
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .$type
  ).prop(
    "objectUnion2",
    $("union")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .item($("object")
          .prop(
            "a",
            $()
              .designType("string")
              .type(String)
              .value("a")
              .$type
          )
          .$type)
      .$type
  ).prop(
    "objectIntersection",
    $("intersection")
      .item($("object")
          .prop(
            "a",
            $()
              .designType("string")
              .type(String)
              .value("a")
              .$type
          )
          .$type)
      .item($("object")
          .prop(
            "b",
            $()
              .designType("string")
              .type(String)
              .value("b")
              .$type
          )
          .$type)
      .$type
  ).prop(
    "grouping",
    $("union")
      .item($()
          .designType("string")
          .type(String)
          .$type)
      .item($("union")
          .item($("intersection")
              .item($("intersection")
                  .item($()
                      .designType("number")
                      .type(Number)
                      .$type)
                  .item($()
                      .designType("boolean")
                      .type(Boolean)
                      .$type)
                  .$type)
              .item($("object")
                  .prop(
                    "a",
                    $()
                      .designType("string")
                      .type(String)
                      .value("b")
                      .$type
                  )
                  .$type)
              .$type)
          .item($()
              .designType("string")
              .type(String)
              .value("c")
              .$type)
          .$type)
      .$type
  )
