/**
 * 🪄 This file was generated by Anscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AnscriptMetadata {
    label: string
    mul: (number)[]
    "long.nested.name": string
    "long.nested.name2": string
    obj: { prop1: string, prop2: number, prop3: boolean }
    nested: boolean
    id: string
    "bool.flag": boolean
  }
}
