// prettier-ignore-start
/* eslint-disable */
/// <reference path="./multiple-interface.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript"

/**
 * Atscript type **TContactType**
 * @see {@link ./multiple-interface.as:1:6}
 */
declare type TContactType = "phone" | "email"
declare namespace TContactType {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex
  const metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = TContactType>(opts?: TValidatorOptions) => Validator<TT>
}

/**
 * Atscript interface **Address**
 * @see {@link ./multiple-interface.as:3:18}
 */
export declare class Address {
  line1: string
  line2: string
  city: string
  state: string
  zip: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = Address>(opts?: TValidatorOptions) => Validator<TT>
}

/**
 * Atscript interface **Contact**
 * @see {@link ./multiple-interface.as:11:11}
 */
declare class Contact {
  type: TContactType
  value: string
  label?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Contact>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = Contact>(opts?: TValidatorOptions) => Validator<TT>
}

/**
 * Atscript interface **User**
 * @see {@link ./multiple-interface.as:17:18}
 */
export declare class User {
  firstName: string
  lastName: string
  address: Address
  contacts: Contact[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof User>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = User>(opts?: TValidatorOptions) => Validator<TT>
}
// prettier-ignore-end