// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "multiple-interface.as".
 * Do not edit this file!
*/

type TContactType = "phone" | "email";

export class Address {
  line1!: string;
  
  line2!: string;
  
  city!: string;
  
  state!: string;
  
  zip!: string;
  
  static get __anscriptMeta(): any {
    return {}
  }
}

interface Contact {
  type: TContactType;
  value: string;
  label?: string;
}

export class User {
  firstName!: string;
  
  lastName!: string;
  
  address!: Address;
  
  contacts!: Contact[];
  
  static get __anscriptMeta(): any {
    return {}
  }
}

// prettier-ignore-end
