// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "multiple-interface.as"
 * Do not edit this file!
 */

declare type TContactType = "phone" | "email"

export declare class Address {
  line1: string
  line2: string
  city: string
  state: string
  zip: string
}

declare class Contact {
  type: TContactType
  value: string
  label?: string
}

export declare class User {
  firstName: string
  lastName: string
  address: Address
  contacts: Contact[]
}
// prettier-ignore-end