// prettier-ignore-start
/* eslint-disable */
/// <reference path="./multiple-interface.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript type **TContactType**
 * @see {@link ./multiple-interface.as:1:6}
 */
declare type TContactType = "phone" | "email"
declare namespace TContactType {
  type DataType = TContactType
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeComplex<TContactType>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<TAtscriptAnnotatedType, TContactType>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
}

/**
 * Atscript interface **Address**
 * @see {@link ./multiple-interface.as:3:18}
 */
export declare class Address {
  line1: string
  line2: string
  city: string
  state: string
  zip: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace Address {
  type DataType = Address
}


/**
 * Atscript interface **Contact**
 * @see {@link ./multiple-interface.as:11:11}
 */
declare class Contact {
  type: TContactType
  value: string
  label?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Contact, Contact>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Contact>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
declare namespace Contact {
  type DataType = Contact
}


/**
 * Atscript interface **User**
 * @see {@link ./multiple-interface.as:17:18}
 */
export declare class User {
  firstName: string
  lastName: string
  address: Address
  contacts: Contact[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof User, User>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof User>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace User {
  type DataType = User
}

// prettier-ignore-end