// prettier-ignore-start
/* eslint-disable */
/// <reference path="./phantom-custom.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **MyForm**
 * @see {@link ./phantom-custom.as:1:18}
 */
export declare class MyForm {
  name: string
  // info: ui.paragraph
  email: string /* email */
  // resetPassword: ui.action
  optional?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof MyForm, MyForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MyForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
// prettier-ignore-end