// prettier-ignore-start
/* eslint-disable */
/// <reference path="./prop-patterns.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **WithPatterns**
 * @see {@link ./prop-patterns.as:1:18}
 */
export declare class WithPatterns {
  prop1: string
  nested: {
    [key: string]: 
      | number
      | string
  } & WithPatterns2
  [key: string]: 
    | string
    | {[key: string]:| number| string} & WithPatterns2
    | number
    | boolean
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof WithPatterns, WithPatterns>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof WithPatterns>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@ts.buildJsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
export declare namespace WithPatterns {
  type DataType = WithPatterns
}


/**
 * Atscript interface **WithPatterns2**
 * @see {@link ./prop-patterns.as:11:11}
 */
declare class WithPatterns2 {
  [key: string]: boolean
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof WithPatterns2, WithPatterns2>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof WithPatterns2>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@ts.buildJsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
}
declare namespace WithPatterns2 {
  type DataType = WithPatterns2
}

// prettier-ignore-end