// prettier-ignore-start
/* eslint-disable */
/// <reference path="./prop-patterns.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **WithPatterns**
 * @see {@link ./prop-patterns.as:1:18}
 */
export declare class WithPatterns {
  prop1: string
  nested: {
    [key: string]: 
      | number
      | string
  } & WithPatterns2
  [key: string]: 
    | string
    | {[key: string]:| number| string} & WithPatterns2
    | number
    | boolean
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof WithPatterns>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof WithPatterns>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}

/**
 * Atscript interface **WithPatterns2**
 * @see {@link ./prop-patterns.as:11:11}
 */
declare class WithPatterns2 {
  [key: string]: boolean
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof WithPatterns2>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = typeof WithPatterns2>(opts?: Partial<TValidatorOptions>) => Validator<TT>
  static toJsonSchema: () => any
}
// prettier-ignore-end