// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "real-world-1.as"
 * Do not edit this file!
 */

declare class Address {
  line1: string
  line2?: string
  city: string
  state: string
  zip: string
}

declare class Contact {
  name: string
  type: "phone" | "email"
  value: string
}

export declare class Entity {
  id: string
  name: string
  address: Address
  contacts: Contact[]
}
// prettier-ignore-end