// prettier-ignore-start
/* eslint-disable */
/**
 * 🪄 This file was generated by Anscript from "real-world-1.as".
 * Do not edit this file!
*/
import { defineAnnotatedType, type TAnscriptTypeObject } from '@anscript/typescript/runtime';

declare class Address {
  line1: string;
  
  line2?: string;
  
  city: string;
  
  state: string;
  
  zip: string;
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

declare class Contact {
  name: string;
  
  type: "phone" | "email";
  
  value: string;
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

export class Entity {
  id: string;
  
  name: string;
  
  address: Address;
  
  contacts: Contact[];
  
  static __is_anscript_annotated_type: boolean;
  
  static type: TAnscriptTypeObject;
  
  static metadata: any;
}

// prettier-ignore-end
