// prettier-ignore-start
/* eslint-disable */
/// <reference path="./real-world-1.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TMetadataMap, Validator } from "@atscript/typescript"

/**
 * Atscript interface **Address**
 * @see {@link ./real-world-1.as:2:11}
 */
declare class Address {
  line1: string
  line2?: string
  city: string
  state: string
  zip: string
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}

/**
 * Atscript interface **Contact**
 * @see {@link ./real-world-1.as:20:11}
 */
declare class Contact {
  name: string
  type: "phone" | "email"
  value: string
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Contact, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}

/**
 * Atscript interface **Entity**
 * @see {@link ./real-world-1.as:26:18}
 */
export declare class Entity {
  id: string
  name: string
  address: Address
  contacts: Contact[]
  static __is_anscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Entity, AnscriptPrimitiveFlags>
  static metadata: TMetadataMap<AnscriptMetadata>
  static validator: () => Validator
}
// prettier-ignore-end