// prettier-ignore-start
/* eslint-disable */
/// <reference path="./type.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TMetadataMap, Validator } from "@atscript/typescript"

/**
 * Atscript type **TPrimitive**
 * @see {@link ./type.as:1:13}
 */
export type TPrimitive = string

/**
 * Atscript type **TPirmiitiveUn**
 * @see {@link ./type.as:3:13}
 */
export type TPirmiitiveUn = string | number

/**
 * Atscript type **TLiteral**
 * @see {@link ./type.as:5:13}
 */
export type TLiteral = "value"

/**
 * Atscript type **TNumber**
 * @see {@link ./type.as:7:13}
 */
export type TNumber = 5

/**
 * Atscript type **TTuple1**
 * @see {@link ./type.as:9:13}
 */
export type TTuple1 = [string]

/**
 * Atscript type **TTuple2**
 * @see {@link ./type.as:11:13}
 */
export type TTuple2 = [string, string]

/**
 * Atscript type **TTupleArray**
 * @see {@link ./type.as:13:13}
 */
export type TTupleArray = [string, string][]

/**
 * Atscript type **TArray**
 * @see {@link ./type.as:15:13}
 */
export type TArray = string[]

/**
 * Atscript type **TArray2**
 * @see {@link ./type.as:17:13}
 */
export type TArray2 = string[][]

/**
 * Atscript type **TArray3**
 * @see {@link ./type.as:19:13}
 */
export type TArray3 = string[][][]

/**
 * Atscript type **TComplexArray**
 * @see {@link ./type.as:21:13}
 */
export type TComplexArray = (string | number)[]

/**
 * Atscript type **TComplexArray2**
 * @see {@link ./type.as:23:13}
 */
export type TComplexArray2 = (string | number)[][]

/**
 * Atscript type **TComplexArray3**
 * @see {@link ./type.as:25:13}
 */
export type TComplexArray3 = (string | number)[][][]

/**
 * Atscript type **TComplexArray4**
 * @see {@link ./type.as:27:13}
 */
export type TComplexArray4 = string | number[]

/**
 * Atscript type **TComplexArray5**
 * @see {@link ./type.as:29:13}
 */
export type TComplexArray5 = string[] | number

/**
 * Atscript type **TObject**
 * @see {@link ./type.as:31:13}
 */
export type TObject = {
  prop1: string
  prop2?: number
  nested: {
    prop3: boolean
    prop4?: boolean
  }
}

/**
 * Atscript type **TObjectUnion1**
 * @see {@link ./type.as:40:13}
 */
export type TObjectUnion1 = {
  a: "a"
} | string

/**
 * Atscript type **TObjectUnion2**
 * @see {@link ./type.as:42:13}
 */
export type TObjectUnion2 = string | {
  a: "a"
}

/**
 * Atscript type **TObjectIntersection**
 * @see {@link ./type.as:44:13}
 */
export type TObjectIntersection = {
  a: "a"
} & {
  b: "b"
}
// prettier-ignore-end