// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./union-type-alias-ref.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **PlaygroundForm**
 * @see {@link ./union-type-alias-ref.as:2:18}
 */
export declare class PlaygroundForm {
  addresses: (Address | Contact | string)[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PlaygroundForm, PlaygroundForm>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof PlaygroundForm>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Address**
 * @see {@link ./union-type-alias-ref.as:8:11}
 */
declare class Address {
  type: "address"
  street: string
  city: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Address, Address>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Address>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **Contact**
 * @see {@link ./union-type-alias-ref.as:15:11}
 */
declare class Contact {
  type: "phone"
  email: string
  phone: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Contact, Contact>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Contact>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript type **MyString**
 * @see {@link ./union-type-alias-ref.as:22:6}
 */
declare type MyString = string
declare namespace MyString {
  const __is_atscript_annotated_type: true
  const type: TAtscriptTypeFinal<MyString>
  const metadata: TMetadataMap<AtscriptMetadata>
  const validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof MyString>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  const toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  const toExampleData: (() => any) | undefined
}
// prettier-ignore-end