// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./agg-orders.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AggOrders**
 * @see {@link ./agg-orders.as:2:18}
 */
export declare class AggOrders {
  id: number
  status: string
  region: string
  amount: number
  quantity: number
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AggOrders, AggOrders>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AggOrders>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "status": string
    "region": string
    "amount": number
    "quantity": number
    "name": string
  }
  static __ownProps: {
    "id": number
    "status": string
    "region": string
    "amount": number
    "quantity": number
    "name": string
  }
  
  static __pk: number
  
  static __dim: "status" | "region"
  static __measure: "amount" | "quantity"
}

/**
 * Atscript interface **PlainEvents**
 * @see {@link ./agg-orders.as:23:18}
 */
export declare class PlainEvents {
  id: number
  category: string
  value: number
  label: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PlainEvents, PlainEvents>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof PlainEvents>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "category": string
    "value": number
    "label": string
  }
  static __ownProps: {
    "id": number
    "category": string
    "value": number
    "label": string
  }
  
  static __pk: number
}

/**
 * Atscript interface **IndexedMetrics**
 * @see {@link ./agg-orders.as:33:18}
 */
export declare class IndexedMetrics {
  id: number
  channel: string
  source: string
  code: string
  revenue: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof IndexedMetrics, IndexedMetrics>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof IndexedMetrics>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "channel": string
    "source": string
    "code": string
    "revenue": number
  }
  static __ownProps: {
    "id": number
    "channel": string
    "source": string
    "code": string
    "revenue": number
  }
  
  static __pk: number | string
  
  static __dim: "channel" | "source" | "code"
  static __measure: "revenue"
}
// prettier-ignore-end