// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-task.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Tag } from "./rel-tag.as"
import { TaskTag } from "./rel-task-tag.as"

/**
 * Atscript interface **Task**
 * @see {@link ./rel-task.as:5:18}
 */
export declare class Task {
  id: number
  title: string
  tags?: Tag[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Task, Task>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Task>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "title": string
    "tags"?: never
    "tags.id"?: number
    "tags.name"?: string
  }
  static __ownProps: {
    "id": number
    "title": string
  }
  
  static __navProps: {
    "tags"?: Tag[]
  }
  
  static __pk: number
}
// prettier-ignore-end