// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./restrict-user.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Project } from "./restrict-project.as"
import { Category } from "./restrict-category.as"

/**
 * Atscript interface **User**
 * @see {@link ./restrict-user.as:5:18}
 */
export declare class User {
  id: number
  name: string
  projects?: Project[]
  categories?: Category[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof User, User>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof User>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "projects"?: never
    "projects.id"?: number
    "projects.title"?: string
    "projects.ownerId"?: number /* id */
    "projects.owner"?: never
    "projects.owner.id"?: number
    "projects.owner.name"?: string
    "projects.owner.projects"?: Project[]
    "projects.owner.categories"?: never
    "projects.owner.categories.id"?: number
    "projects.owner.categories.label"?: string
    "projects.owner.categories.ownerId"?: number /* id */
    "projects.owner.categories.owner"?: {
      id: number
      name: string
      projects?: Project[]
      categories?: Category[]
    }
    "categories"?: never
    "categories.id"?: number
    "categories.label"?: string
    "categories.ownerId"?: number /* id */
    "categories.owner"?: never
    "categories.owner.id"?: number
    "categories.owner.name"?: string
    "categories.owner.projects"?: never
    "categories.owner.projects.id"?: number
    "categories.owner.projects.title"?: string
    "categories.owner.projects.ownerId"?: number /* id */
    "categories.owner.projects.owner"?: {
      id: number
      name: string
      projects?: Project[]
      categories?: Category[]
    }
    "categories.owner.categories"?: Category[]
  }
  static __ownProps: {
    "id": number
    "name": string
  }
  
  static __navProps: {
    "projects"?: Project[]
    "categories"?: Category[]
  }
  
  static __pk: number
}
// prettier-ignore-end