// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./agg-orders.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AggOrders**
 * @see {@link ./agg-orders.as:2:18}
 */
export declare class AggOrders {
  id: number
  status: string
  currency: string
  amount: number
  quantity: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AggOrders, AggOrders>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AggOrders>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "status": string
    "currency": string
    "amount": number
    "quantity": number
  }
  static __ownProps: {
    "id": number
    "status": string
    "currency": string
    "amount": number
    "quantity": number
  }
  
  static __pk: number
  
  static __dim: "status" | "currency"
  static __measure: "amount" | "quantity"
}
// prettier-ignore-end