// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./collate.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **AccountTable**
 * @see {@link ./collate.as:2:18}
 */
export declare class AccountTable {
  id: number
  nickname: string
  email: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof AccountTable, AccountTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof AccountTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "nickname": string
    "email": string
  }
  static __ownProps: {
    "id": number
    "nickname": string
    "email": string
  }
  
  static __pk: number
}
// prettier-ignore-end