// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./vector-table.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **ArticlesTable**
 * @see {@link ./vector-table.as:2:18}
 */
export declare class ArticlesTable {
  id: string
  title: string
  embedding: number[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ArticlesTable, ArticlesTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ArticlesTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "title": string
    "embedding": number[]
  }
  static __ownProps: {
    "id": string
    "title": string
    "embedding": number[]
  }
  
  static __pk: string
}
// prettier-ignore-end