// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./cycle-b.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { CycleA } from "./cycle-a.as"

/**
 * Atscript interface **CycleB**
 * @see {@link ./cycle-b.as:4:18}
 */
export declare class CycleB {
  id: number
  name: string
  aId?: number /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CycleB, CycleB>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CycleB>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "aId"?: number /* id */
  }
  static __ownProps: {
    "id": number
    "name": string
    "aId"?: number /* id */
  }
  
  static __pk: number
}
// prettier-ignore-end