// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-tag.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **Tag**
 * @see {@link ./rel-tag.as:2:18}
 */
export declare class Tag {
  id: number
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Tag, Tag>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Tag>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
  }
  static __ownProps: {
    "id": number
    "name": string
  }
  
  static __pk: number
}
// prettier-ignore-end