/**
 * 🪄 This file was generated by Anscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AnscriptMetadata {
    'mongo.collection': string
    'mongo.index.plain': (string | true)[]
    'mongo.index.unique': (string | true)[]
    'mongo.index.text': number | true
    'mongo.dynamicTextSearch': { analyzer?: string; fuzzy?: number; indexName?: string }
    'mongo.defineTextSearch': { indexName: string; analyzer?: string; fuzzy?: number }[]
    'mongo.useTextSearch': { indexName: string; analyzer?: string }[]
    'mongo.vectorIndex': { dimensions: number; similarity?: string; indexName?: string }
    'mongo.vectorFilter': { indexName: string }[]
  }
  type AnscriptPrimitiveFlags =
    | 'never'
    | 'string'
    | 'email'
    | 'phone'
    | 'number'
    | 'positive'
    | 'negative'
    | 'single'
    | 'double'
    | 'int'
    | 'boolean'
    | 'true'
    | 'false'
    | 'null'
    | 'void'
    | 'undefined'
    | 'mongo'
    | 'objectId'
    | 'vector'
}
