/**
 * 🪄 This file was generated by Atscript
 * It is generated based on annotations used in this project
 * Do not edit this file!
 *
 * Use `npx asc -f dts` command to re-generate this file
 */
export {}

declare global {
  interface AtscriptMetadata {
    'mongo.collection': string
    'mongo.index.plain': Array<string | true>
    'mongo.index.unique': Array<string | true>
    'mongo.index.text': number | true
    'mongo.search.dynamic': { analyzer?: string; fuzzy?: number }
    'mongo.search.static': Array<{ analyzer?: string; fuzzy?: number; indexName?: string }>
    'mongo.search.text': Array<{ analyzer?: string; indexName?: string }>
    'mongo.search.vector': { dimensions: number; similarity?: string; indexName?: string }
    'mongo.search.filter': Array<{ indexName: string }>
    'mongo.patch.strategy': string
    'mongo.array.key': boolean
  }
  type AtscriptPrimitiveTags =
    | 'never'
    | 'string'
    | 'email'
    | 'phone'
    | 'number'
    | 'positive'
    | 'negative'
    | 'single'
    | 'double'
    | 'int'
    | 'boolean'
    | 'true'
    | 'false'
    | 'null'
    | 'void'
    | 'undefined'
    | 'mongo'
    | 'objectId'
    | 'vector'
}
