// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./default-fns.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **TokenTable**
 * @see {@link ./default-fns.as:2:18}
 */
export declare class TokenTable {
  id: string
  label: string
  createdAt?: number /* timestamp.created */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TokenTable, TokenTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TokenTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": string
    "label": string
    "createdAt"?: number /* timestamp.created */
  }
  static __ownProps: {
    "id": string
    "label": string
    "createdAt"?: number /* timestamp.created */
  }
  
  static __pk: string
}

/**
 * Atscript interface **CounterTable**
 * @see {@link ./default-fns.as:14:18}
 */
export declare class CounterTable {
  id: number
  label: string
  createdAt?: number /* timestamp.created */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof CounterTable, CounterTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof CounterTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "label": string
    "createdAt"?: number /* timestamp.created */
  }
  static __ownProps: {
    "id": number
    "label": string
    "createdAt"?: number /* timestamp.created */
  }
  
  static __pk: number
}

/**
 * Atscript interface **SimpleCounterTable**
 * @see {@link ./default-fns.as:26:18}
 */
export declare class SimpleCounterTable {
  id: number
  label: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SimpleCounterTable, SimpleCounterTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SimpleCounterTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "label": string
  }
  static __ownProps: {
    "id": number
    "label": string
  }
  
  static __pk: number
}
// prettier-ignore-end