// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./test-table.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **UsersTable**
 * @see {@link ./test-table.as:3:18}
 */
export declare class UsersTable {
  id: number
  email: string
  name: string
  createdAt: number
  displayName?: string
  status: string
  bio?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UsersTable, UsersTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UsersTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **NoTableAnnotation**
 * @see {@link ./test-table.as:29:18}
 */
export declare class NoTableAnnotation {
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NoTableAnnotation, NoTableAnnotation>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NoTableAnnotation>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end