// prettier-ignore-start
/* eslint-disable */
/// <reference path="./controls.dto.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type {
  TAtscriptTypeObject,
  TAtscriptTypeComplex,
  TAtscriptTypeFinal,
  TAtscriptTypeArray,
  TMetadataMap,
  Validator,
  TValidatorOptions,
} from '@atscript/typescript'

/**
 * Atscript interface **QueryControlsDto**
 * @see {@link ./controls.dto.as:1:18}
 */
export declare class QueryControlsDto {
  $skip?: number /* int.positive */
  $limit?: number /* int.positive */
  $count?: boolean
  $sort?: SortControlDto
  $select?: SelectControlDto
  $search?: string
  $index?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof QueryControlsDto, QueryControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof QueryControlsDto>
}
export declare namespace QueryControlsDto {
  type DataType = QueryControlsDto
}

/**
 * Atscript interface **PagesControlsDto**
 * @see {@link ./controls.dto.as:11:18}
 */
export declare class PagesControlsDto {
  $page?: string
  $size?: string
  $sort?: SortControlDto
  $select?: SelectControlDto
  $search?: string
  $index?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PagesControlsDto, PagesControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof PagesControlsDto>
}
export declare namespace PagesControlsDto {
  type DataType = PagesControlsDto
}

/**
 * Atscript interface **GetOneControlsDto**
 * @see {@link ./controls.dto.as:22:18}
 */
export declare class GetOneControlsDto {
  $select?: SelectControlDto
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof GetOneControlsDto, GetOneControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof GetOneControlsDto>
}
export declare namespace GetOneControlsDto {
  type DataType = GetOneControlsDto
}

/**
 * Atscript interface **SortControlDto**
 * @see {@link ./controls.dto.as:26:11}
 */
declare class SortControlDto {
  [key: string]: 1 | -1
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SortControlDto, SortControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SortControlDto>
}
declare namespace SortControlDto {
  type DataType = SortControlDto
}

/**
 * Atscript interface **SelectControlDto**
 * @see {@link ./controls.dto.as:30:11}
 */
declare class SelectControlDto {
  [key: string]: 1 | 0
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SelectControlDto, SelectControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SelectControlDto>
}
declare namespace SelectControlDto {
  type DataType = SelectControlDto
}
// prettier-ignore-end
