// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./controls.dto.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **QueryControlsDto**
 * @see {@link ./controls.dto.as:1:18}
 */
export declare class QueryControlsDto {
  $skip?: number /* int.positive */
  $limit?: number /* int.positive */
  $count?: boolean
  $sort?: SortControlDto
  $select?: SelectControlDto
  $search?: string
  $index?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof QueryControlsDto, QueryControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof QueryControlsDto>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **PagesControlsDto**
 * @see {@link ./controls.dto.as:11:18}
 */
export declare class PagesControlsDto {
  $page?: string
  $size?: string
  $sort?: SortControlDto
  $select?: SelectControlDto
  $search?: string
  $index?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PagesControlsDto, PagesControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof PagesControlsDto>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **GetOneControlsDto**
 * @see {@link ./controls.dto.as:22:18}
 */
export declare class GetOneControlsDto {
  $select?: SelectControlDto
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof GetOneControlsDto, GetOneControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof GetOneControlsDto>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **SortControlDto**
 * @see {@link ./controls.dto.as:26:11}
 */
declare class SortControlDto {
  [key: string]: 1 | -1
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SortControlDto, SortControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SortControlDto>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **SelectControlDto**
 * @see {@link ./controls.dto.as:30:11}
 */
declare class SelectControlDto {
  [key: string]: 1 | 0
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SelectControlDto, SelectControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof SelectControlDto>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}
// prettier-ignore-end