// prettier-ignore-start
/* eslint-disable */
/// <reference path="./controls.dto.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TMetadataMap, Validator, TAtscriptAnnotatedTypeConstructor, TValidatorOptions } from "@atscript/typescript"

/**
 * Atscript interface **QueryControlsDto**
 * @see {@link ./controls.dto.as:1:18}
 */
export declare class QueryControlsDto {
  $skip?: number /* int.positive */
  $limit?: number /* int.positive */
  $count?: boolean
  $sort?: SortControlDto
  $select?: SelectControlDto
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof QueryControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = QueryControlsDto>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}

/**
 * Atscript interface **PagesControlsDto**
 * @see {@link ./controls.dto.as:9:18}
 */
export declare class PagesControlsDto {
  $page?: string
  $size?: string
  $sort?: SortControlDto
  $select?: SelectControlDto
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof PagesControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = PagesControlsDto>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}

/**
 * Atscript interface **GetOneControlsDto**
 * @see {@link ./controls.dto.as:18:18}
 */
export declare class GetOneControlsDto {
  $select?: SelectControlDto
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof GetOneControlsDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = GetOneControlsDto>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}

/**
 * Atscript interface **SortControlDto**
 * @see {@link ./controls.dto.as:22:11}
 */
declare class SortControlDto {
  [key: string]: 1 | -1
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SortControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = SortControlDto>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}

/**
 * Atscript interface **SelectControlDto**
 * @see {@link ./controls.dto.as:26:11}
 */
declare class SelectControlDto {
  [key: string]: 1 | 0
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof SelectControlDto>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: <TT extends TAtscriptAnnotatedTypeConstructor = SelectControlDto>(opts?: Partial<TValidatorOptions>) => Validator<TT>
}
// prettier-ignore-end