// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-author.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Post } from "./test-relations.as"

/**
 * Atscript interface **Author**
 * @see {@link ./rel-author.as:4:18}
 */
export declare class Author {
  id: number
  name: string
  createdAt?: number /* timestamp.created */
  posts?: Post[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Author, Author>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Author>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "createdAt"?: number /* timestamp.created */
    "posts"?: never
    "posts.id"?: number
    "posts.title"?: string
    "posts.status"?: string
    "posts.createdAt"?: number /* timestamp.created */
    "posts.authorId"?: number /* id */
    "posts.author"?: never
    "posts.author.id"?: number
    "posts.author.name"?: string
    "posts.author.createdAt"?: number /* timestamp.created */
    "posts.author.posts"?: Post[]
    "posts.comments"?: never
    "posts.comments.id"?: number
    "posts.comments.body"?: string
    "posts.comments.createdAt"?: number /* timestamp.created */
    "posts.comments.postId"?: number /* id */
    "posts.comments.post"?: never
    "posts.comments.post.id"?: number
    "posts.comments.post.title"?: string
    "posts.comments.post.status"?: string
    "posts.comments.post.createdAt"?: number /* timestamp.created */
    "posts.comments.post.authorId"?: number /* id */
    "posts.comments.post.author"?: never
    "posts.comments.post.author.id"?: number
    "posts.comments.post.author.name"?: string
    "posts.comments.post.author.createdAt"?: number /* timestamp.created */
    "posts.comments.post.author.posts"?: Post[]
    "posts.comments.post.comments"?: Comment[]
  }
  static __pk: number
}
// prettier-ignore-end