// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-task-tag.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Task } from "./rel-task.as"
import { Tag } from "./rel-tag.as"

/**
 * Atscript interface **TaskTag**
 * @see {@link ./rel-task-tag.as:5:18}
 */
export declare class TaskTag {
  id: number
  taskId: number /* id */
  tagId: number /* id */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof TaskTag, TaskTag>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof TaskTag>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "taskId": number /* id */
    "tagId": number /* id */
  }
  static __ownProps: {
    "id": number
    "taskId": number /* id */
    "tagId": number /* id */
  }
  
  static __pk: number
}
// prettier-ignore-end