// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-author.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Post } from "./test-relations.as"

/**
 * Atscript interface **Author**
 * @see {@link ./rel-author.as:4:18}
 */
export declare class Author {
  id: number
  name: string
  createdAt?: number /* timestamp.created */
  posts?: Post[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Author, Author>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Author>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "createdAt"?: number /* timestamp.created */
    "posts"?: Post[]
  }
  static __pk: number
}
// prettier-ignore-end