// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-comment.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Post } from "./test-relations.as"

/**
 * Atscript interface **Comment**
 * @see {@link ./rel-comment.as:4:18}
 */
export declare class Comment {
  id: number
  body: string
  createdAt?: number /* timestamp.created */
  postId: Post["id"]
  post?: Post
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Comment, Comment>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Comment>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "body": string
    "createdAt"?: number /* timestamp.created */
    "postId": Post["id"]
    "post"?: Post
  }
  static __pk: number
}
// prettier-ignore-end