// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./rel-comment.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Post } from "./test-relations.as"

/**
 * Atscript interface **Comment**
 * @see {@link ./rel-comment.as:4:18}
 */
export declare class Comment {
  id: number
  body: string
  createdAt?: number /* timestamp.created */
  postId: number /* id */
  post?: Post
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Comment, Comment>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Comment>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "body": string
    "createdAt"?: number /* timestamp.created */
    "postId": number /* id */
    "post"?: never
    "post.id"?: number
    "post.title"?: string
    "post.status"?: string
    "post.createdAt"?: number /* timestamp.created */
    "post.authorId"?: Author["id"]
    "post.author"?: never
    "post.author.id"?: number
    "post.author.name"?: string
    "post.author.createdAt"?: number /* timestamp.created */
    "post.author.posts"?: never
    "post.author.posts.id"?: number
    "post.author.posts.title"?: string
    "post.author.posts.status"?: string
    "post.author.posts.createdAt"?: number /* timestamp.created */
    "post.author.posts.authorId"?: Author["id"]
    "post.author.posts.author"?: {
      id: number
      name: string
      createdAt?: number /* timestamp.created */
      posts?: Post[]
    }
    "post.author.posts.comments"?: never
    "post.author.posts.comments.id"?: number
    "post.author.posts.comments.body"?: string
    "post.author.posts.comments.createdAt"?: number /* timestamp.created */
    "post.author.posts.comments.postId"?: number /* id */
    "post.author.posts.comments.post"?: {
      id: number
      title: string
      status: string
      createdAt?: number /* timestamp.created */
      authorId: Author["id"]
      author?: Author
      comments?: Comment[]
    }
    "post.comments"?: never
    "post.comments.id"?: number
    "post.comments.body"?: string
    "post.comments.createdAt"?: number /* timestamp.created */
    "post.comments.postId"?: number /* id */
    "post.comments.post"?: {
      id: number
      title: string
      status: string
      createdAt?: number /* timestamp.created */
      authorId: Author["id"]
      author?: Author
      comments?: Comment[]
    }
  }
  static __pk: number
}
// prettier-ignore-end