// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./restrict-project.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { User } from "./restrict-user.as"

/**
 * Atscript interface **Project**
 * @see {@link ./restrict-project.as:4:18}
 */
export declare class Project {
  id: number
  title: string
  ownerId: number /* id */
  owner?: User
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Project, Project>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Project>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "title": string
    "ownerId": number /* id */
    "owner"?: never
    "owner.id"?: number
    "owner.name"?: string
    "owner.projects"?: never
    "owner.projects.id"?: number
    "owner.projects.title"?: string
    "owner.projects.ownerId"?: number /* id */
    "owner.projects.owner"?: {
      id: number
      name: string
      projects?: Project[]
      categories?: Category[]
    }
    "owner.categories"?: never
    "owner.categories.id"?: number
    "owner.categories.label"?: string
    "owner.categories.ownerId"?: number /* id */
    "owner.categories.owner"?: {
      id: number
      name: string
      projects?: Project[]
      categories?: Category[]
    }
  }
  static __ownProps: {
    "id": number
    "title": string
    "ownerId": number /* id */
  }
  
  static __navProps: {
    "owner"?: User
  }
  
  static __pk: number
}
// prettier-ignore-end