// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./test-table.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"

/**
 * Atscript interface **UsersTable**
 * @see {@link ./test-table.as:3:18}
 */
export declare class UsersTable {
  id: number
  email: string
  name: string
  createdAt: number
  displayName?: string
  status: string
  bio?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof UsersTable, UsersTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof UsersTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "email": string
    "name": string
    "createdAt": number
    "displayName"?: string
    "status": string
    "bio"?: string
  }
  static __ownProps: {
    "id": number
    "email": string
    "name": string
    "createdAt": number
    "displayName"?: string
    "status": string
    "bio"?: string
  }
  
  static __pk: number | string
}

/**
 * Atscript interface **ProfileTable**
 * @see {@link ./test-table.as:30:18}
 */
export declare class ProfileTable {
  id: number
  name: string
  contact: {
    email: string
    phone?: string
  }
  preferences: {
    theme: string
    lang: string
  }
  tags: string[]
  settings: {
    notifications: {
      email: boolean
      sms: boolean
    }
  }
  displayName?: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ProfileTable, ProfileTable>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ProfileTable>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "name": string
    "contact": never
    "contact.email": string
    "contact.phone"?: string
    "preferences": string
    "tags": string[]
    "settings": never
    "settings.notifications": never
    "settings.notifications.email": boolean
    "settings.notifications.sms": boolean
    "displayName"?: string
  }
  static __ownProps: {
    "id": number
    "name": string
    "contact": never
    "contact.email": string
    "contact.phone"?: string
    "preferences": string
    "tags": string[]
    "settings": never
    "settings.notifications": never
    "settings.notifications.email": boolean
    "settings.notifications.sms": boolean
    "displayName"?: string
  }
  
  static __pk: number
}

/**
 * Atscript interface **NoTableAnnotation**
 * @see {@link ./test-table.as:61:18}
 */
export declare class NoTableAnnotation {
  name: string
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof NoTableAnnotation, NoTableAnnotation>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof NoTableAnnotation>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
}

/**
 * Atscript interface **ActiveUsersView**
 * @see {@link ./test-table.as:68:18}
 */
export declare class ActiveUsersView {
  id: number /* id */
  name: string /* name */
  email: string /* email */
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof ActiveUsersView, ActiveUsersView>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof ActiveUsersView>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number /* id */
    "name": string /* name */
    "email": string /* email */
  }
  static __ownProps: {
    "id": number /* id */
    "name": string /* name */
    "email": string /* email */
  }
}

/**
 * Atscript interface **LegacyReportView**
 * @see {@link ./test-table.as:75:18}
 */
export declare class LegacyReportView {
  id: number
  total: number
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof LegacyReportView, LegacyReportView>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof LegacyReportView>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "total": number
  }
  static __ownProps: {
    "id": number
    "total": number
  }
}
// prettier-ignore-end