// prettier-ignore-start
/* eslint-disable */
/* oxlint-disable */
/// <reference path="./test-relations.as" />
/**
 * 🪄 This file was generated by Atscript
 * Do not edit this file!
 */

import type { TAtscriptTypeObject, TAtscriptTypeComplex, TAtscriptTypeFinal, TAtscriptTypeArray, TAtscriptAnnotatedType, TMetadataMap, Validator, TValidatorOptions } from "@atscript/typescript/utils"
import { Author } from "./rel-author.as"
import { Comment } from "./rel-comment.as"

/**
 * Atscript interface **Post**
 * @see {@link ./test-relations.as:5:18}
 */
export declare class Post {
  id: number
  title: string
  status: string
  createdAt?: number /* timestamp.created */
  authorId: Author["id"]
  author?: Author
  comments?: Comment[]
  static __is_atscript_annotated_type: true
  static type: TAtscriptTypeObject<keyof Post, Post>
  static metadata: TMetadataMap<AtscriptMetadata>
  static validator: (opts?: Partial<TValidatorOptions>) => Validator<typeof Post>
  /** @deprecated JSON Schema support is disabled. Calling this method will throw a runtime error. To enable, set `jsonSchema: 'lazy'` or `jsonSchema: 'bundle'` in tsPlugin options, or add `@emit.jsonSchema` annotation to individual interfaces. */
  static toJsonSchema: () => any
  /** @deprecated Example Data support is disabled. To enable, set `exampleData: true` in tsPlugin options. */
  static toExampleData?: () => any
  static __flat: {
    "id": number
    "title": string
    "status": string
    "createdAt"?: number /* timestamp.created */
    "authorId": Author["id"]
    "author"?: Author
    "comments"?: Comment[]
  }
  static __pk: number
}
// prettier-ignore-end