import { TAnscriptPlugin } from '@ts-anscript/core'
import { TypeRenderer, JsRenderer } from './codegen'
import path from 'path'
import { escapeQuotes, wrapProp } from './codegen/utils'

export const tsPlugin: () => TAnscriptPlugin = () => {
  return {
    name: 'typesccript',
    render(doc, format) {
      if (format === 'dts') {
        return [
          {
            fileName: `${doc.name}.d.ts`,
            content: new TypeRenderer(doc).render(),
          },
        ]
      }
      if (format === 'js') {
        return [
          {
            fileName: `${doc.name}.js`,
            content: new JsRenderer(doc).render(),
          },
        ]
      }
    },

    async buildEnd(output, format, repo) {
      if (format === 'dts') {
        // render anscript.d.ts
        const annotations = await repo.getUsedAnnotations()
        const flags = (await repo.getPrimitivesFlags()) || new Set()
        let rendered = [] as string[]
        for (const [key, val] of Object.entries(annotations)) {
          const multiple = val!.multiple
          let typeLine = Array.from(val!.types)
            .map(t => {
              if (t.type === 'object') {
                return `{ ${Object.entries(t.props)
                  .map(([k, v]) => `${wrapProp(k)}${v.optional ? '?' : ''}: ${v.type}`)
                  .join(', ')} }`
              } else {
                return t.optional ? `${t.type} | true` : t.type
              }
            })
            .join(' | ')
          rendered.push(
            `${wrapProp(key)}: ${multiple ? '(' : ''}${typeLine}${multiple ? ')[]' : ''}`
          )
        }
        let renderedFlags = Array.from(flags)
          .map(f => `"${escapeQuotes(f)}"`)
          .join(' | ')
        output.push({
          content:
            '/**\n' +
            ' * 🪄 This file was generated by Anscript\n' +
            ' * It is generated based on annotations used in this project\n' +
            ' * Do not edit this file!\n' +
            ' *\n' +
            ' * Use `npx asc -f dts` command to re-generate this file\n' +
            ' */\n' +
            'export {}\n\n' +
            'declare global {\n' +
            '  interface AnscriptMetadata {\n    ' +
            rendered.join('\n    ') +
            '\n  }\n' +
            '  type AnscriptPrimitiveFlags = ' +
            renderedFlags +
            '\n' +
            '}\n',
          fileName: 'anscript.d.ts',
          source: '',
          target: path.join(repo.root, 'anscript.d.ts'),
        })
      }
    },
  } as TAnscriptPlugin
}
